export const AREAS_TRABALHO = [
  'Administração',
  'Agronegócio',
  'Arquitetura e Urbanismo',
  'Atendimento ao Cliente',
  'Auditoria',
  'Ciência de Dados e Analytics',
  'Ciências Contábeis',
  'Comercial e Vendas',
  'Comunicação e Relações Públicas',
  'Compliance e Governança',
  'Construção Civil e Engenharia',
  'Contabilidade e Fiscal',
  'Design e Criação',
  'Direito e Jurídico',
  'E-commerce e Marketplace',
  'Educação e Treinamento',
  'Engenharia Elétrica',
  'Engenharia Mecânica',
  'Engenharia de Produção',
  'Engenharia de Software',
  'Estoque e Almoxarifado',
  'Eventos e Hospitalidade',
  'Financeiro e Controladoria',
  'Gestão de Projetos',
  'Gestão de Qualidade',
  'Infraestrutura de TI',
  'Logística e Supply Chain',
  'Marketing Digital',
  'Marketing Tradicional',
  'Medicina e Saúde',
  'Meio Ambiente e Sustentabilidade',
  'Nutrição',
  'Operações e Processos',
  'Pedagogia e Ensino',
  'Pesquisa e Desenvolvimento',
  'Psicologia',
  'Recursos Humanos',
  'Relações Internacionais',
  'Saúde e Segurança do Trabalho',
  'Secretariado e Assistência',
  'Segurança da Informação',
  'Seguros',
  'Serviço Social',
  'Suporte Técnico',
  'Telecomunicações',
  'Tecnologia da Informação',
  'Turismo e Hotelaria',
]

export const REGIMES = [
  'CLT',
  'PJ',
  'Estágio',
  'Temporário',
  'Freelancer',
  'Trainee',
]

export const MODALIDADES = [
  'Presencial',
  'Híbrido',
  'Remoto',
]

export const ESTADOS_BR = [
  'AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO',
  'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI',
  'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO',
]
